# This is a GitHub action to auto format code on a push or a pull request to the master branch
name: auto-format

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "format"
  format:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # format everything in the src directory
      - name: Run clang-format
        run: clang-format -i src/*
        
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes from clang-format (automatically)
          branch: ${{ github.head_ref }}
